### ISSUE TITLE
Create "How to get involved" page

### ISSUE THREAD

**Issue by nmalky** [sourcebots/volunteer-docs#16] opened 2018-03-19 20:55 UTC
Name idea: "getting-involved.md"?
This might include things other than just contributing code.

- Meetings that exist
- Joining the communication platforms (e.g. slack, google groups mailing list)
- Contributing code
[TODO: add some more things!]

Closely related to Quick start page.

**Comment by trickeydan** [comment] 2018-03-19 22:14
Duplicate of #8

**Closed by trickeydan** 2018-03-19 22:14 UTC
Labels: new content
